global:
  scrape_interval: 15s
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: [ 'localhost:9090' ]
  - job_name: 'invoicer-nginx'
    scheme: http
    bearer_token: 'sample'
    static_configs:
      - targets: [ 'invoicer-nginx:4000' ]