ktor:
  application:
    modules:
      - io.github.alaksion.invoicer.server.app.ApplicationKt.module
  deployment:
    port: $INVOICER_API_PORT
database:
  name: $INVOICER_DB_NAME
  username: $INVOICER_DB_USERNAME
  password: $INVOICER_DB_PASSWORD
  url: $INVOICER_DB_URL
jwt:
  audience: $INVOICER_JWT_AUDIENCE
  issuer: $INVOICER_JWT_ISSUER
  secret: $INVOICER_JWT_SECRET
  realm: $INVOICER_JWT_REALM
redis:
  port: $INVOICER_REDIS_PORT
  host: $INVOICER_REDIS_HOST
  ttl: $INVOICER_REDIS_TTL
minIO:
  key: $INVOICER_MIN_IO_ACCESS_KEY
  secret: $INVOICER_MIN_IO_SECRET_KEY
  url: $INVOICER_MIN_IO_URL