ktor:
  application:
    modules:
      - io.github.monolithic.invoicer.server.app.ApplicationKt.module
  deployment:
    port: $INVOICER_API_PORT
database:
  name: $INVOICER_DB_NAME
  username: $INVOICER_DB_USERNAME
  password: $INVOICER_DB_PASSWORD
  url: $INVOICER_DB_URL
jwt:
  audience: $INVOICER_JWT_AUDIENCE
  issuer: $INVOICER_JWT_ISSUER
  secret: $INVOICER_JWT_SECRET
  realm: $INVOICER_JWT_REALM
redis:
  port: $INVOICER_REDIS_PORT
  host: $INVOICER_REDIS_HOST
kafka:
  bootstrap_servers: $INVOICER_KAFKA_BOOTSTRAP_SERVERS
firebase:
  project_id: $INVOICER_FIREBASE_PROJECT_ID
  service_account_file: $INVOICER_FIREBASE_SERVICE_ACCOUNT_FILE
file_upload:
  bucket_pdfs: $INVOICER_PDF_UPLOAD_BUCKET
email:
  resend_api_key: $INVOICER_RESEND_API_KEY
s3:
  endpoint: $INVOICER_S3_ENDPOINT
  access_key: $INVOICER_S3_ACCESS_KEY
  secret_key: $INVOICER_S3_SECRET_KEY