ktor:
  application:
    modules:
      - io.github.alaksion.invoicer.server.app.ApplicationKt.module
  deployment:
    port: 8080
#database:
#  name: $INVOICER_DB_NAME
#  username: $INVOICER_DB_USERNAME
#  password: $INVOICER_DB_PASSWORD
#  url: $INVOICER_DB_URL
#jwt:
#  audience: $INVOICER_JWT_AUDIENCE
#  issuer: $INVOICER_JWT_ISSUER
#  secret: $INVOICER_JWT_SECRET
#  realm: $INVOICER_JWT_REALM
