[versions]
ktorm = "4.0.0"
kodein = "7.22.0"
open-pdf = "2.0.2"

[libraries]
ktorm = { module = "org.ktorm:ktorm-core", version.ref = "ktorm" }
kodein-server = { module = "org.kodein.di:kodein-di-framework-ktor-server-jvm", version.ref = "kodein" }
openpdf = { module = "com.github.librepdf:openpdf", version.ref = "open-pdf" }

[plugins]